### PR TITLE
Fix a segfault in `get_local_var`

### PR DESCRIPTION
**Pull request by buixor**
If we are not in a function yet, `get_local_var` will trigger a crash, because `symtable` will be NULL and then `ZEND_HASH_FOREACH_STR_KEY_VAL` will NULL-deref.

### CODE REVIEW

**Comment by jvoisin** [comment]
Care to provide a test for this?

**Comment by buixor** [comment]
yes, this was just a quick fix according to a provided coredump.
Looking to understand how ` EG(current_execute_data)` can be made `NULL` in a test to trigger the bug (which apparently would trigger `zend_rebuild_symbol_table()` to return `NULL`).


(cf. https://github.com/php/php-src/pull/1482)

**Comment by jvoisin** [comment]
In `Zend.c`, the `zend_error` function:

```C

			symbol_table = zend_rebuild_symbol_table();

			/* during shutdown the symbol table table can be still null */
			if (!symbol_table) {
				ZVAL_NULL(&params[4]);
			} else {
				ZVAL_ARR(&params[4], zend_array_dup(symbol_table));
			}
```

**Comment by jvoisin** [comment]
So yeah, apparently, it can be NULL and must be taken care of.
```
/* {{{ proto array get_defined_vars(void)
   Returns an associative array of names and values of all currently defined variable names (variables in the current scope) */
ZEND_FUNCTION(get_defined_vars)
{
	zend_array *symbol_table;
	if (zend_forbid_dynamic_call("get_defined_vars()") == FAILURE) {
		return;
	}

	symbol_table = zend_rebuild_symbol_table();
	if (UNEXPECTED(symbol_table == NULL)) {
		return;
	}

	RETURN_ARR(zend_array_dup(symbol_table));
}
/* }
```

**Comment by buixor** [comment]
`ob_start` seems a good suspect

**Comment by buixor** [comment]
I think I got it :

```
<?php
function foo() {
 strlen("42");
 print "foo\n";
}
    ob_start(foo);
    print "finished\n";

?>
```

```
sp.disable_function.function("strlen").var("$i").value("42").drop();
```

**Pull request merged**
